# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_registrationcode_subscription_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationcode',
            old_name='max_use',
            new_name='max_users',
        ),
        migrations.RemoveField(
            model_name='registrationcode',
            name='subscription_required',
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='unlimited_use',
            field=models.BooleanField(default=False),
        ),
    ]
