# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_auto_20160909_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
