# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0007_auto_20160916_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(default='greys', max_length=15),
        ),
    ]
