# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0008_userprofile_color_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionhistory',
            old_name='stripe_confirm',
            new_name='payment_id',
        ),
    ]
