# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0009_auto_20170608_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
